apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    # Email address used for ACME registration
    email: {{ .Values.clusterIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: {{ .Values.clusterIssuer.privateSecretRef | quote }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    {{- with .Values.clusterIssuer.solvers}}
      {{- toYaml . | nindent 4 }}
    {{- end }}