apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm_chart.name" . }}-mysecrets
type: Opaque
stringData:
  DATABASE_URL: postgres://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Values.db.host }}/{{ .Values.db.name }}